#+TITLE:     Daily GIT
#+html_head: <link rel="stylesheet" type="text/css" href="../css/article.css" />
#+html_head: <link rel="stylesheet" type="text/css" href="../css/toc.css" />
#+INDEX: git

* Git Concept
** Terms

| name         | explanation                                                                                                      |
|--------------+------------------------------------------------------------------------------------------------------------------|
| repository   | A *repository* is a collection of *commits*                                                                      |
| staging area | Before changes of *working tree* are committed to *repository*, it goes to *staging area* first.                 |
| working tree | A derectory on file system which has a *repository* associated to it.                                            |
| commit       | A *commit* is a snapshot of your *working tree* at some point in time                                            |
| branch       | A *branch* is a name for a *commit*, also called a *reference*.                                                  |
| tag          | A *tag* is also a name of a *commit*, but it always names the same commit and can have its own description text. |
| master       | the mainline of development branch                                                                               |
| HEAD         | *HEAD* indicates what is checked out in current *working tree*.                                                  |

** Readings
  - [[http://git-scm.com/book/][Pro Git]]
  - [[http://eagain.net/articles/git-for-computer-scientists/][Git for Computer Scientists]]
  - [[http://ftp.newartisans.com/pub/git.from.bottom.up.pdf][Git from Bottom Up]]
  - [[http://tom.preston-werner.com/2009/05/19/the-git-parable.html][The Git Parable]]
  - [[http://git-scm.com/documentation][Git Documentation]]
  - [[http://git.wiki.kernel.org/][Git wiki]]

* Git Basic
** Create a new repository locally
#+begin_src sh
git init
#+end_src
** Get repository from a remote server
#+begin_src sh
git clone <URL>
#+end_src

** Current status
#+begin_src sh
git status
#+end_src
** Diff changes
#+begin_src sh
git diff <FILE>
#+end_src
** Diff with another branch
#+begin_src sh
git diff <another-branch>
#+end_src
** Staging changes
#+begin_src sh
git add <FILE>
#+end_src
** Diff staged changes
#+begin_src sh
git diff --cached
#+end_src
** Check whitespaces errors
#+begin_src sh
git diff --check
#+end_src

** Commit changes
#+begin_src sh
git commit
#+end_src
** Commit/Checkout/Stage Interactively
#+begin_src sh
git commit -p <file>
git checkout -p <file>
git add -p <file>
#+end_src
** Branches
   Show branch(es)
#+begin_src sh
git branch
#+end_src

   Check out remote branch
#+begin_src sh
git checkout -b <local-branch> origin/<remote-branch>
#+end_src

   It is commom enough to use same local branch name, so git provide shorthand like this
#+begin_src sh
git checkout --track origin/<remote-branch>
#+end_src

   push local branch to remote server:
#+begin_src sh
git push remote <branch>
#+end_src

   to delete a remote branch
#+begin_src sh
git push origin --delete <branch>
#+end_src
** List Tags
#+begin_src sh
git tag -l
#+end_src
** Checkout a specific tag
#+begin_src sh
git checkout tags/<tagname>
#+end_src
** Roll back commitment

   When you have done some bad commit on a branch like this:
#+begin_src sh
A - B - C - D - E - F
#+end_src
   and you want to roll back to /C/ and discard /D/, /E/ and /F/.

   First, you shold will need the hash id of /C/, the first several number is sufficient (db7c2b7 for example).

   Then execute the reset command of git:
#+begin_src sh
git reset --soft db7c2b7
#+end_src
   or you want to discard the changes you have made forever (before you do it, think about it twice):
#+begin_src sh
git reset --hard db7c2b7
#+end_src
   After reset the branch, the commitment /D/, /E/, and /F/ are removed. Next time you commit some thing, it will directly behind /C/.

   If you have a remote repository and you want to change it also, push the resetting like this:
#+begin_src sh
git push --force origin
#+end_src

   To get a list of HEADs with =reflog=
#+begin_src sh
git reflog
#+end_src

** Git behind proxy
   - install socat
#+begin_src sh
   $ sudo apt-get install socat
#+end_src
   - create proxy-cmd.sh containing (replace your_proxy and your_proxy_port)
#+begin_src sh
   #!/bin/bash
   socat STDIO PROXY:your_proxy:$1:$2,proxyport=your_proxy_port
#+end_src
   - change perm and export
#+begin_src sh
   $ chmod +x proxy-cmd.sh
   $ export GIT_PROXY_COMMAND=proxy-cmd.sh
#+end_src

** Ignore SSL certification
#+begin_src sh
env GIT_SSL_NO_VERIFY=true git clone https://github...
#+end_src

** Automatic template for commit messages
   You can set a global template for all git projects.
#+begin_src sh
  git config --global commit.template ~/.git-commit-message.global
#+end_src
   Or you can set a local template for a specific project.
#+begin_src sh
  cd <path/to/project>; git config --local commit.template <path/to/template>
#+end_src

** Setup user name and email
#+begin_src sh
  git config --global user.name <user name>
  git config --global user.email <user@domain.com>
#+end_src

* Git Advance
** Make a bare repository
#+begin_src sh
git clone --bare /path/to/original/code
#+end_src
** Stash changes
#+begin_src sh
git stash
#+end_src
   Diff against stash
#+begin_src sh
git stash show -p stash@{0}
#+end_src
   See more details [[http://git-scm.com/book/en/Git-Tools-Stashing][here]].

** Use rebase to merge branches
   Use rebase can avoid one refence has more than one parent after merge.

** Histories
   filter logs by author
#+begin_src sh
git log --author='@google.com'
#+end_src
   formating out put with ISO date, author Email and subject.
#+begin_src sh
git log --format=format:"%aD %aE %s"
#+end_src
   history as a graph
#+begin_src sh
git log --graph --branches --oneline --decorate
#+end_src
** History of every line of a file
#+begin_src sh
git blame <filename>
#+end_src
   or
#+begin_src sh
git annotate <filename>
#+end_src
** Find changed files between commits
#+begin_src sh
git diff --name-only <ci1> <ci2>
#+end_src

* Git Configuration

* Gitosis (Obsoleted)
** Installation and Configuration
   Install gitosis
#+begin_src sh
   $ sudo apt-get install gitosis
#+end_src
   You might want to put repositories in /home/git/ rather than /srv/gitosis/.
#+begin_src sh
   $ sudo usermod -d /home/git/ gitosis
#+end_src
   Or add a new git management user
#+begin_src sh
   $ sudo adduser \
   --system \
   --shell /bin/sh \
   --gecos 'git verison control' \
   --group \
   --disabled-password \
   --home /home/git \
   git
#+end_src
   You will need a public ssh key to continue.
#+begin_src sh
   $ ssh-keygen -t rsa
#+end_src
   Then initialize the gitosis repository with the rss key.
#+begin_src sh
   $ sudo -H -u gitosis gitosis-init < /tmp/id_dsa.pub
#+end_src
   You'll see messages like this.
#+begin_src sh
   Initialized empty Git repository in /home/git/repositories/gitosis-admin.git/
   Reinitialized existing Git repository in /home/git/repositories/gitosis-admin.git/
#+end_src
   Now you can get the admin files
#+begin_src sh
   $ git clone git@HOST:gitosis-admin.git
#+end_src
** Add Users
   Gather users' SSH public key and add them to gitosis-admin.
#+begin_src sh
   $ cd gitosis-admin
   $ cp ~/alice.pub ~/bob.pub keydir/
   $ git add keydir/
#+end_src
   Change gitosis.conf
#+begin_src sh
[group myteam]
- member = fw  
+ member = fw alice bob  
writable = project
#+end_src
   The push it to the git repository.
#+begin_src sh
   $ git commit -a -m 'Granted Alice and Bob commit rights to project'
   $ git push
#+end_src
** Add Repositories
   Change the gitosis.conf
#+begin_src sh
[group mygroup] 
members = member1 member2 member3
writable = projectA projectB
#+end_src
   The push it to the gitosis-admin.

   Add a project
#+begin_src sh
mdkir projectA
cd projectA
git init
git add .
git remote add origin git@HOST:projectA.git
do some work
git push origin master:refs/heads/master
#+end_src
** Public Access
#+begin_src sh
  sudo -u git git-daemon --base-path=/home/git/repositories/ --export-all
#+end_src


* Github
** config SSH client
   Generate ssh key pair, key pair will be found in ~/.ssh/ by default.
#+begin_src sh
  ssh-keygen -t dsa -C <email>
#+end_src

   Upload .ssh/id_dsa.pub to github.com. (check setting -> ssh key after login to github.com)

   If you're behind a proxy, install corkscrew first.
#+begin_src sh
  sudo dnf install corkscrew
#+end_src

   Then configure ssh by editing =.ssh/config=.
#+begin_src sh
  host github.com
    hostname ssh.github.com
    user git
    port 443
    ProxyCommand corkscrew proxy.domain.com port %h %p
    IdentityFile ~/.ssh/id_dsa
#+end_src

   Some proxy server may block port 22, so you have to use =ssh.github.com=
   as server address and =443= as port.

   For direct access without proxy, =.ssh/config= will be easier.
#+begin_src sh
  host github.com
    user git
    IdentityFile ~/.ssh/id_dsa
#+end_src

   Now you can try if your setup is working
#+begin_src sh
ssh -T github.com
#+end_src

   If it works, you will see message like this
: Hi Name! You've successfully authenticated, but GitHub does not provide shell access.

   Congrats! Now you can pull/push your code from/to github through SSH.


* Git Best Practices
** Branching Model
   - [[http://git-scm.com/book/ch3-4.html][basic model]]
   - more complex [[http://nvie.com/posts/a-successful-git-branching-model/][example]]
