#+TITLE:     Managing virtual devices on Linux with libvirt
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/article.css" />
#+html_head: <link rel="stylesheet" type="text/css" href="../css/toc.css" />

* Install tools

Install necessary tools for the demo.
#+BEGIN_SRC bash
sudo apt install qemu-kvm qemu-system-x86 libvirt-clients \
                 libvirt-daemon-system virtinst cloud-utils whois -y
#+END_SRC
Then grant access right of KVM and libvirt to current user.
#+BEGIN_SRC bash
sudo usermod -aG kvm $USER
sudo usermod -aG libvirt $USER
#+END_SRC

Check if everything is OK.
#+BEGIN_SRC bash
$ kvm-ok
  INFO: /dev/kvm exists
  KVM acceleration can be used

$ virsh list
 Id   Name   State
--------------------
#+END_SRC

* Setup VM with libvirt

** Setup bridged network (optional)

Create a bridge `br0` and set NIC `eno1` as it's interface.
#+BEGIN_SRC bash
sudo apt install bridge-utils -y
sudo brctl addbr br0
sudo brctl addif br0 eno1
#+END_SRC

Then bring up `br0` with `netplan`.
#+BEGIN_SRC bash
cat <<EOF | sudo tee /etc/netplan/00-installer-config.yaml
network:
    ethernets:
        eno1:
            dhcp4: no
    bridges:
        br0:
            dhcp4: yes
            interfaces:
                - eno1
    version: 2'
EOF
sudo netplan apply
#+END_SRC

Apply bridged network to `libvirt`
#+BEGIN_SRC bash
cat <<EOF > /tmp/bridged-network.xml
<network>
    <name>bridged-network</name>
    <forward mode="bridge" />
    <bridge name="br0" />
</network>
EOF
virsh net-define /tmp/bridged-network.xml
virsh net-start bridged-network
virsh net-autostart bridged-network
#+END_SRC

** Create root image

You can choose whatever version you need, for simplicity,
I'll use Ubuntu 20.04 minimal cloud image in this demo.
#+BEGIN_SRC bash
wget http://cloud-images.ubuntu.com/minimal/releases/focal/release-20211130/ubuntu-20.04-minimal-cloudimg-amd64.img
#+END_SRC

Make sure that file type of downloaded image is *qcow*.
#+END_SRCconsole
$ qemu-img info ubuntu-20.04-minimal-cloudimg-amd64.img

image: ubuntu-20.04-minimal-cloudimg-amd64.img
file format: qcow2
virtual size: 2.2 GiB (2361393152 bytes)
disk size: 245 MiB
cluster_size: 65536
Format specific information:
    compat: 0.10
    refcount bits: 16
#+END_SRC
For less confusion, rename base image.
#+BEGIN_SRC bash
mv ubuntu-20.04-minimal-cloudimg-amd64.img ubuntu-20.04-minimal-cloudimg-amd64.qcow
#+END_SRC

Create root image of VM and enlarge disk size.
#+BEGIN_SRC bash
$ qemu-img convert -f qcow2 -O qcow2 ubuntu-20.04-minimal-cloudimg-amd64.qcow2 disk.qcow2

$ qemu-img  resize disk.qcow2 128G

$ qemu-img info disk.qcow2

image: disk.qcow2
file format: qcow2
virtual size: 128 GiB (137438953472 bytes)
disk size: 33.9 GiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
#+END_SRC

** Create user data

Generate password which you are going to use in the virtual machine.
#+BEGIN_SRC bash
$ mkpasswd --method=SHA-512 --rounds=4096
Password:
$6$rounds=4096$JD68ijyq6bBiLCcP$PtUuzIUCNPnXWiBK/w7lkZnjg4PmIVeAufcKqFgVwWpCjujybiubO/xkt12o8qHCgi7wx4.nCQPhAPMoc1adb.
#+END_SRC

Generate SSH key
#+BEGIN_SRC bash
$ ssh-keygen -C "eii-virtual-machine"
$ cat ~/.ssh/id_rsa.pub
ssh-rsa AAAAB3... eii-virtual-machine
#+END_SRC

Create user data file for [cloud-init](https://cloudinit.readthedocs.io/en/latest/).
#+BEGIN_SRC bash
cat user-data
#+END_SRC

#+BEGIN_SRC yaml
#cloud-config
hostname: vm-eii
manage_etc_hosts: true
timezone: Asia/Chongqing
users:
  - default
  - name: eii
    gecos: John Doe
    lock_passwd: false
    passwd: $6$rounds=4096$JD68ijy...adb.
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/eii
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-rsa AAAAB3...eii-virtual-machine

apt:
  primary:
    - arches: [default]
      uri: http://mirrors.aliyun.com/ubuntu/

packages:
  - vim
  - git
  - docker.io
  - docker-compose

package_update: true
package_upgrade: true
#+END_SRC

Then create image of user data.
#+BEGIN_SRC bash
cloud-localds user-data.img user-data
#+END_SRC

** Start virtual machine with libvirt CLI

The parameters of libvirt CLI is a bit messy. For simplicity, I created a shell script to create the virtual machine.

#+BEGIN_SRC bash
cat <<EOF > install-eii-vm.sh
#!/usr/bin/env bash
VM_NAME=eii
VCPUS="10"
RAM_MB="8192"

virt-install \
    --connect="qemu:///system" \
    --name="${VM_NAME}" \
    --vcpus="${VCPUS}" \
    --memory="${RAM_MB}" \
    --os-variant="ubuntu20.04" \
    --disk $PWD/disk.qcow2,device=disk,bus=virtio \
    --disk $PWD/user-data.img,format=raw \
    --virt-type kvm \
    --graphics none \
    --import
EOF
chmod +x install-eii-vm.sh
#+END_SRC
Then run this script to create the virtual machine named *eii* in background.
#+BEGIN_SRC bash
./install-eii-vm.sh
#+END_SRC

Now you can check the state of *eii* you just created.
#+BEGIN_SRC bash
$ virsh list
 Id   Name   State
----------------------
 1    eii    running
#+END_SRC

** Connect to the VM

There are two ways to connect to the VM: using `virsh console` command or `ssh`.

- With `virsh console`
#+BEGIN_SRC bash
$ virsh console eii
Connected to domain eii
Escape character is ^] <press Enter>

eii@vm-eii:~$ ip addr show dev enp1s0 scope global
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:b8:8f:cb brd ff:ff:ff:ff:ff:ff
    inet 10.238.156.118/23 brd 10.238.157.255 scope global dynamic enp1s0
       valid_lft 2884sec preferred_lft 2884sec
#+END_SRC

- With `ssh`

#+BEGIN_SRC bash
$ ssh eii@<vm-ip-addr>
#+END_SRC

To get ip address of VM if bridged network is used:
#+BEGIN_SRC bash
$ arp -an | grep $(virsh dumpxml eii | grep "mac address" | awk -F\' '{ print $2}')
? (10.238.156.118) at 52:54:00:b8:8f:cb [ether] on br0
#+END_SRC
Otherwise use virsh command:
#+BEGIN_SRC bash
virsh net-dhcp-leases default
#+END_SRC

** Change VM settings

Read the manual for more details.
#+BEGIN_SRC bash
virsh setmem eii <new-memory-size>
virsh setvcpu eii <new-cores>
#+END_SRC
