#+TITLE:     Linux Tricks
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/article.css" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/toc.css" />

* Terminal Emulator

** Mononoki font cannot be found by gnome terminal
   This issue is caused by mis-typing of mononoki font as a none mono.
   To force gnome terninal use it, install =dconf-editor=, find
   =/org/gnome/terminal/legacy/profile:/:<uuid>/font=, type =mononoki <size>=
   in "Custom value".

   Or use other terminal emulators such as =terminator= which comes with more 
   features such as split window.

* Boot to Non-graphical Mode

  For a server running Ubuntu, all users will be login through SSH or VNC,
  graphical mode is not needed. To boot to text mode by default, we need to
  change both GRUB and system configuration.

#+BEGIN_SRC sh
sudo vim /etc/default/grub
#+END_SRC

  Find line of GRUB default setting and do the change.
: # GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
: GRUB_CMDLINE_LINUX_DEFAULT="quiet splash text"

  Then update GRUB configuration by =update-grub= command.

#+BEGIN_SRC sh
sudo update-grub
#+END_SRC

  To update system configuration, user =systemctl= command.

#+BEGIN_SRC sh
sudo systemctl set-default multi-user.target
#+END_SRC

  Default setting can be restore by =systemctl= command.

#+BEGIN_SRC sh
sudo systemctl set-default graphical.target
#+END_SRC

* Setup WiFi from Terminal
  [[https://www.linuxbabe.com/ubuntu/connect-to-wi-fi-from-terminal-on-ubuntu-18-04-19-04-with-wpa-supplicant][ref]]
#+BEGIN_SRC sh
  # Use iwconfig to find WiFi interface
  $ iwconfig

  # Find available AP
  $ sudo iwlist wlp1s0 scan | grep ESSID

  # Setup WPA_Supplicant
  $ wpa_passphrase <ESSID> <password> | sudo tee /etc/wap_supplicant.conf

  $ sudo wpa_supplicant -B -c /etc/wpa_supplicant.conf -i wlp1s0
  $ sudo dhclient wlp1s0
  $ ip addr wlp1s0
#+END_SRC

* Using LVM

** Extending Logical Volume.
#+BEGIN_SRC sh
  sudo lvextend -L +100GB /dev/ubuntu-vg/ubuntu-lv
  sudo resize2fs /dev/ubuntu-vg/ubuntu-lv
#+END_SRC

** Extending Logical Volume to Whole Disk
#+BEGIN_SRC sh
  sudo lvresize -l +100%FREE /dev/ubuntu-vg/ubuntu-lv
#+END_SRC

* Configuring systemd-timesyncd
Default NTP server may not working behind corporate proxies. To enable the corporate NTP server, if there is one, edit =/etc/systemd/timesyncd.conf=

#+BEGIN_SRC 
[Time]
NTP=ntp.yourcorp.com
#+END_SRC

Then restart timesyncd.

#+BEGIN_SRC sh
  sudo systemctl restart systemd-timesyncd
#+END_SRC

Now check if it works.

#+BEGIN_SRC sh
  sudo systemctl status systemd-timesyncd
#+END_SRC

* Proxy

** General Setting

For local users, add these lines in =~/.profile= if using bash, =~/.zshenv= if zsh.
For all users, add to =/etc/environment=.
#+BEGIN_SRC sh
  export http_proxy="http://proxy.host:port"
  export https_proxy="http://proxy.host:port"
#+END_SRC

** APT

Edit =/etc/apt/apt.conf.d/80proxy=
#+BEGIN_SRC conf
  Acquire {
    HTTP::Proxy "http://proxy.host:port";
    HTTPS::Proxy "http://proxy.host:port";
  }
#+END_SRC

** Snap

#+BEGIN_SRC sh
snap set system proxy.http="http://proxy.host:port"
snap set system proxy.https="http://proxy.host:port"
#+END_SRC
