#+TITLE:     Ubuntu + CUDA + Tensorflow + PyTorch
#+html_head: <link rel="stylesheet" type="text/css" href="../css/article.css" />
#+html_head: <link rel="stylesheet" type="text/css" href="../css/toc.css" />

#+INDEX: tensorflow, pytorch, cuda

* Install Ubuntu 18.04
  Should be easy.

* Install Nvidia Device Driver
  Add PPA repository of Nvidia drivers.
#+begin_src sh
  sudo add-apt-repository ppa:graphics-drivers/ppa
#+end_src

  List Nvidia devices
#+begin_src sh
  lspci | grep VGA
#+end_src

#+begin_example
  01:00.0 VGA compatible controller: NVIDIA Corporation Device 1f07 (rev a1)
#+end_example

  List available drivers
#+begin_src sh
  sudo ubuntu-drivers devices
#+end_src
#+begin_example
  == /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 ==
  modalias : pci:v000010DEd00001F07sv00001043sd00008681bc03sc00i00
  vendor   : NVIDIA Corporation
  driver   : nvidia-driver-415 - third-party free
  driver   : nvidia-driver-418 - third-party free
  driver   : nvidia-driver-410 - third-party free
  driver   : nvidia-driver-430 - third-party free recommended
  driver   : xserver-xorg-video-nouveau - distro free builtin
#+end_example

  Install recommended driver
#+begin_src sh
  sudo ubuntu-drivers install
#+end_src

  Check installation
#+begin_src sh
  nvidia-smi
#+end_src
* Install CUDA/CUDNN toolkit
  Should be easy.

* Setup Python Environment
** Setup VirtualEnv
#+begin_src sh
  sudo apt install virtualenv
  virtualenv -p /usr/bin/python3 .env
  . .env/bin/activate
#+end_src

** Managing Python packages with *pip*
#+begin_src sh
  # install package
  pip install <package_name>

  # update package
  pip install -U <package_name>

  # check outdated packages
  pip list --outdated

  # check installed packages
  pip freeze > requirements.txt

  # install requirements
  pip install -r requirements.txt
#+end_src

*** Using local *pip* mirrors
    Create file =~/.pip/pip.conf=
#+begin_src
  [global]
  #index-url = https://mirrors.ustc.edu.cn/pypi/web/simple
  trusted-host = mirrors.aliyun.com
  index-url = http://mirrors.aliyun.com/pypi/simple
  format = columns
#+end_src

* Install TensorFlow
  Install the stable version with GPU supported.
#+begin_src sh
  pip install tensorflow-gpu
#+end_src
  Install specific version.
#+begin_src sh
  pip install tensorflow-gpu==1.14.0
#+end_src

  The "Conv2D CUDNN handle issue"[fn:1][fn:2]
#+begin_src python
  # for tf 1.x
  config = tf.ConfigProto(allow_soft_placement=True)
  config.gpu_options.allow_growth = True
  sess = tf.Session(config=config)

  # for tf 2.0
  gpus = tf.config.experimental.list_physical_devices('GPU')
  for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
#+end_src

** Build TensorFlow from source code[fn:3]
   Download tensorflow source code
#+begin_src sh
  git clone git@github.com:tensorflow/tensorflow.git
  git checkout r1.9
#+end_src

   Install bazel
#+begin_src sh
  wget https://github.com/bazelbuild/bazel/releases/download/0.26.1/bazel-0.26.1-installer-linux-x86_64.sh
  chmod a+x *.sh
  ./bazel-0.26.1-installer-linux-x86_64.sh --prefix=~/.local
  # set PATH if not yet
  # export PATH=$PATH:~/.local/bin
#+end_src

* Install PyTorch
#+begin_src sh
  pip install torch torchvision
#+end_src

* Install MxNet
  To install official release, check [[mxnet.apache.org]].
#+begin_src sh
  pip install mxnet-cu100mkl # for both CUDA 10.0 and MKLDNN
#+end_src

  To install branch with NumPy integrated, check [[numpy.mxnet.io]].
#+begin_src sh
  pip install https://apache-mxnet.s3-accelerate.amazonaws.com/dist/python/numpy/latest/mxnet_cu100mkl-1.5.0-py2.py3-none-manylinux1_x86_64.whl
#+end_src

* Miscs
** Install Matplotlib
#+begin_src sh
sudo apt install python3-tk
pip install matplotlib
#+end_src

** Jupyter Notebook
   Install jupyter notebook.
#+begin_src sh
  pip install jupyter
#+end_src

   Start jupyter notebook
#+begin_src sh
  jupyter notebook
#+end_src

[fn:1] [[https://tensorflow.google.cn/beta/guide/using_gpu][TF Guide: Using GPU]]
[fn:2] [[https://github.com/tensorflow/tensorflow/issues/6698][issue-6698]]
[fn:3] [[https://tensorflow.google.cn/install/source][Build TF from Source]]
