#+TITLE:     Ubuntu Tricks
#+html_head: <link rel="stylesheet" type="text/css" href="../css/article.css" />
#+html_head: <link rel="stylesheet" type="text/css" href="../css/toc.css" />

* Terminal Emulator

** Mononoki font cannot be found by gnome terminal since ubuntu 18.04
   This issue is caused by mis-typing of mononoki font as a none mono.
   To force gnome terninal use it, install =dconf-editor=, find
   =/org/gnome/terminal/legacy/profile:/:<uuid>/font=, type =mononoki <size>=
   in "Custom value".

   Or use other terminal emulators such as =terminator= which comes with more 
   features such as split window.

* Boot to Non-graphical Mode

  For a server running Ubuntu, all users will be login through SSH or VNC,
  graphical mode is not needed. To boot to text mode by default, we need to
  change both GRUB and system configuration.

#+BEGIN_SRC sh
sudo vim /etc/default/grub
#+END_SRC

  Find line of GRUB default setting and do the change.
: # GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
: GRUB_CMDLINE_LINUX_DEFAULT="quiet splash text"

  Then update GRUB configuration by =update-grub= command.

#+BEGIN_SRC sh
sudo update-grub
#+END_SRC

  To update system configuration, user =systemctl= command.

#+BEGIN_SRC sh
sudo systemctl set-default multi-user.target
#+END_SRC

  Default setting can be restore by =systemctl= command.

#+BEGIN_SRC sh
sudo systemctl set-default graphical.target
#+END_SRC

* Setup WiFi from Terminal
  [[https://www.linuxbabe.com/ubuntu/connect-to-wi-fi-from-terminal-on-ubuntu-18-04-19-04-with-wpa-supplicant][ref]]
#+BEGIN_SRC sh
  # Use iwconfig to find WiFi interface
  $ iwconfig

  # Find available AP
  $ sudo iwlist wlp1s0 scan | grep ESSID

  # Setup WPA_Supplicant
  $ wpa_passphrase <ESSID> <password> | sudo tee /etc/wap_supplicant.conf

  $ sudo wpa_supplicant -B -c /etc/wpa_supplicant.conf -i wlp1s0
  $ sudo dhclient wlp1s0
  $ ip addr wlp1s0
#+END_SRC
