#+TITLE:     Deep Learning Setup with Ubuntu
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/article.css" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/toc.css" />
#+INDEX: tensorflow
#+INDEX: pytorch
#+INDEX: cuda
#+INDEX: ubuntu
#+INDEX: mxnet

* Install Ubuntu 22.04
Should be easy.

* Install Nvidia Device Driver
Add PPA repository of Nvidia drivers.
#+BEGIN_SRC sh
  sudo add-apt-repository ppa:graphics-drivers/ppa
#+END_SRC

List Nvidia devices
#+BEGIN_SRC sh
  lspci | grep VGA
#+END_SRC

#+begin_example
  01:00.0 VGA compatible controller: NVIDIA Corporation Device 1f07 (rev a1)
#+end_example

List available drivers
#+BEGIN_SRC sh
  sudo ubuntu-drivers devices
#+END_SRC
#+begin_example
  == /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 ==
  modalias : pci:v000010DEd00001F07sv00001043sd00008681bc03sc00i00
  vendor   : NVIDIA Corporation
  driver   : nvidia-driver-415 - third-party free
  driver   : nvidia-driver-418 - third-party free
  driver   : nvidia-driver-410 - third-party free
  driver   : nvidia-driver-430 - third-party free recommended
  driver   : xserver-xorg-video-nouveau - distro free builtin
#+end_example

Install recommended driver
#+BEGIN_SRC sh
  sudo ubuntu-drivers install
#+END_SRC

Check installation
#+BEGIN_SRC sh
  nvidia-smi
#+END_SRC

* Install CUDA/CUDNN toolkit
Should be easy.

* Setup Python Environment
** Setup VirtualEnv
#+BEGIN_SRC sh
  sudo apt install virtualenv
  virtualenv -p /usr/bin/python3 .env
  . .env/bin/activate
#+END_SRC

** Managing Python packages with *pip*
#+BEGIN_SRC sh
  # install package
  pip install <package_name>

  # update package
  pip install -U <package_name>

  # check outdated packages
  pip list --outdated

  # check installed packages
  pip freeze > requirements.txt

  # install requirements
  pip install -r requirements.txt
#+END_SRC

*** Using local *pip* mirrors
Create file =~/.pip/pip.conf=
#+BEGIN_SRC conf
  [global]
  #index-url = https://mirrors.ustc.edu.cn/pypi/web/simple
  trusted-host = mirrors.aliyun.com
  index-url = http://mirrors.aliyun.com/pypi/simple
  format = columns
#+END_SRC

* Install TensorFlow
Install the stable version with GPU supported.
#+BEGIN_SRC sh
  pip install tensorflow-gpu
#+END_SRC

Install specific version.
#+BEGIN_SRC sh
  pip install tensorflow-gpu==1.14.0
#+END_SRC

The "Conv2D CUDNN handle issue"[fn:1][fn:2]
#+BEGIN_SRC python
  # for tf 1.x
  config = tf.ConfigProto(allow_soft_placement=True)
  config.gpu_OPTIONS.allow_growth = True
  sess = tf.Session(config=config)

  # for tf 2.0
  gpus = tf.config.experimental.list_physical_devices('GPU')
  for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
#+END_SRC

** Build TensorFlow from source code[fn:3]
Download tensorflow source code
#+BEGIN_SRC sh
  git clone git@github.com:tensorflow/tensorflow.git
  git checkout r1.9
#+END_SRC

Install bazel
#+BEGIN_SRC sh
  wget https://github.com/bazelbuild/bazel/releases/download/0.26.1/bazel-0.26.1-installer-linux-x86_64.sh
  chmod a+x *.sh
  ./bazel-0.26.1-installer-linux-x86_64.sh --prefix=~/.local
  # set PATH if not yet
  # export PATH=$PATH:~/.local/bin
#+END_SRC

* Install PyTorch
#+BEGIN_SRC sh
  pip install torch torchvision torchaudio
#+END_SRC

* Install MxNet
To install official release, check [[https://mxnet.apache.org][here]].
#+BEGIN_SRC sh
  pip install mxnet-cu100mkl # for both CUDA 10.0 and MKLDNN
#+END_SRC

To install branch with NumPy integrated, check [[https://numpy.mxnet.io][here]].
#+BEGIN_SRC sh
  pip install https://apache-mxnet.s3-accelerate.amazonaws.com/dist/python/numpy/latest/mxnet_cu100mkl-1.5.0-py2.py3-none-manylinux1_x86_64.whl
#+END_SRC

* Miscs
** Install Matplotlib
#+BEGIN_SRC sh
sudo apt install python3-tk
pip install matplotlib
#+END_SRC

** Jupyter Notebook
Install jupyter notebook.
#+BEGIN_SRC sh
  pip install notebook
#+END_SRC

Start jupyter notebook
#+BEGIN_SRC sh
  jupyter notebook
#+END_SRC

[fn:1] [[https://tensorflow.google.cn/beta/guide/using_gpu][TF Guide: Using GPU]]
[fn:2] [[https://github.com/tensorflow/tensorflow/issues/6698][issue-6698]]
[fn:3] [[https://tensorflow.google.cn/install/source][Build TF from Source]]
